# Generated by Django 4.2.30 on 2026-04-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Quota', 'Quota di Iscrizione'), ('Multa', 'Multa'), ('Premio', 'Premio')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.TextField(blank=True, help_text="Aggiungi una nota (Es. 'Dimenticanza formazioni')", null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Spunta questa casella quando il partecipante ha pagato o ha ricevuto il premio')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
