# Generated by Django 4.2.30 on 2026-04-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Scudetto', 'Scudetto'), ('Coppa Italia', 'Coppa Italia'), ('Supercoppa', 'Supercoppa')], max_length=50)),
                ('year', models.CharField(help_text='Es: 2023/2024', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
